server:
  port: 9002
spring:
  application:
    name: cloud-consumer-order-service
  datasource:
    druid:
      username: root
      password: 6565333
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true&useUnicode=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
    type: com.alibaba.druid.pool.DruidDataSource

